name: Build WireGuard for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 检出仓库
      - name: 检出仓库
        uses: actions/checkout@v4

      # 查看当前目录
      - name: 查看当前目录
        run: |
          dir

      # 执行 build 命令
      - name: 构建WireGuard
        run: build

      # 上传构建的文件（假设 .exe 文件在构建目录下）
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wireguard-windows-build
          path: ./*.exe
